//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEA_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicInfo
    {
        public int AcademicId { get; set; }
        public int StudentId { get; set; }
        public string AdmissionType { get; set; }
        public string Semester { get; set; }
        public string ApplicationYear { get; set; }
        public string Major { get; set; }
    
        public virtual Student_Profile Student_Profile { get; set; }
    }
}
