//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEA_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyCollege
    {
        public int ApplyCollegeId { get; set; }
        public string SchoolName { get; set; }
        public string Semester { get; set; }
        public string CourseApplied { get; set; }
        public string CollegeEmail { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
        public Nullable<int> StudentId { get; set; }
    }
}
