//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEA_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CEAEntities1 : DbContext
    {
        public CEAEntities1()
            : base("name=CEAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AcademicInfo> AcademicInfoes { get; set; }
        public DbSet<AddressStudent> AddressStudents { get; set; }
        public DbSet<ApplyCollege> ApplyColleges { get; set; }
        public DbSet<CitizenShipInfo> CitizenShipInfoes { get; set; }
        public DbSet<ContactMe> ContactMes { get; set; }
        public DbSet<ExamInfo> ExamInfoes { get; set; }
        public DbSet<PreviousSchoolInfo> PreviousSchoolInfoes { get; set; }
        public DbSet<SchoolData> SchoolDatas { get; set; }
        public DbSet<Student_Profile> Student_Profile { get; set; }
        public DbSet<SupportingDoc> SupportingDocs { get; set; }
        public DbSet<WorkInfo> WorkInfoes { get; set; }
    }
}
