//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEA_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitizenShipInfo
    {
        public int CitizenshipId { get; set; }
        public int StudentId { get; set; }
        public string CountryOfCitizenship { get; set; }
        public string Ethnicity { get; set; }
        public string I20Required { get; set; }
        public string VisaStatus { get; set; }
        public string CurrentLocation { get; set; }
        public string VeteranStatus { get; set; }
    
        public virtual Student_Profile Student_Profile { get; set; }
    }
}
