//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEA_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamInfo
    {
        public int ExamId { get; set; }
        public string ExamType { get; set; }
        public Nullable<System.DateTime> DateOfExam { get; set; }
        public string Score { get; set; }
        public Nullable<int> StudentId { get; set; }
    
        public virtual Student_Profile Student_Profile { get; set; }
    }
}
