//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEA_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Profile
    {
        public Student_Profile()
        {
            this.AcademicInfoes = new HashSet<AcademicInfo>();
            this.AddressStudents = new HashSet<AddressStudent>();
            this.CitizenShipInfoes = new HashSet<CitizenShipInfo>();
            this.ExamInfoes = new HashSet<ExamInfo>();
            this.PreviousSchoolInfoes = new HashSet<PreviousSchoolInfo>();
            this.SupportingDocs = new HashSet<SupportingDoc>();
            this.WorkInfoes = new HashSet<WorkInfo>();
        }
    
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string SSN { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string CountryofBirth { get; set; }
        public string Filefordelete { get; set; }
        public Nullable<int> totalFileSize { get; set; }
    
        public virtual ICollection<AcademicInfo> AcademicInfoes { get; set; }
        public virtual ICollection<AddressStudent> AddressStudents { get; set; }
        public virtual ICollection<CitizenShipInfo> CitizenShipInfoes { get; set; }
        public virtual ICollection<ExamInfo> ExamInfoes { get; set; }
        public virtual ICollection<PreviousSchoolInfo> PreviousSchoolInfoes { get; set; }
        public virtual ICollection<SupportingDoc> SupportingDocs { get; set; }
        public virtual ICollection<WorkInfo> WorkInfoes { get; set; }
    }
}
