//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEA_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportingDoc
    {
        public int SupportingDocId { get; set; }
        public string TypeofDoc { get; set; }
        public string ServerURL { get; set; }
        public Nullable<int> StudentId { get; set; }
        public byte[] filecontent { get; set; }
        public string filelength { get; set; }
        public string mimeType { get; set; }
    
        public virtual Student_Profile Student_Profile { get; set; }
    }
}
